# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "hugo-theme-stack"
baseURL = "https://blog.1q77.com/"
defaultContentLanguage = "ja"

enableRobotsTXT = true
paginate = 20
summaryLength = 80
# summary の文字数適正化
hasCJKLanguage = true

rssLimit = 30

buildDrafts = false
buildFuture = false

googleAnalytics = "G-07K1ZG1PVD"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  posts = '/:year/:month/:filename/'
